name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.101
    - name: Install dependencies
      run: dotnet restore src\ProjectEuler.sln
    - name: Build
      run: dotnet build src\ProjectEuler.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test src\ProjectEuler.sln --no-restore --verbosity normal
